---
driver:
  name: vagrant
  customize:
    cpus: 2

provisioner:
  name: itamae

platforms:
  - name: ubuntu-14.04
    provisioner:
      node_json: nodes/node1.json
  - name: centos-6.6
    provisioner:
      sudo_command: sudo su -m -c
      node_json: nodes/node2.json
      run_list:
       - recipes/selinux.rb

suites:
  - name: default
    provisioner:
      with_ohai: true
      itamae_option: "--no-color"
    run_list:
      - roles/default.rb
    attributes:
      attr1: value1
      attr2:
        - ar1
        - ar2
