---
driver:
  name: vagrant

provisioner:
  name: itamae
  itamae_plugins:
    - rbenv
    - selinux

platforms:
  - name: ubuntu-14.04
    provisioner:
      node_json: nodes/node1.json
  - name: centos-6.6
    provisioner:
      node_json: nodes/node2.json
      run_list:
       - recipes/selinux.rb

suites:
  - name: default
    provisioner:
      with_ohai: false
      itamae_option: "--no-color"
      run_list:
        - recipes/package1.rb
        - recipes/package2.rb
        - recipes/file.rb
