---
driver:
  name: vagrant

provisioner:
  name: itamae
  itamae_plugins:
    - rbenv
    - selinux

platforms:
  - name: ubuntu-12.04
    provisioner:
      node_json: nodes/node.json

suites:
  - name: default
    provisioner:
      recipe_list:
        - recipes/package1.rb
        - recipes/package2.rb
